version: '3.8'

services:
  agent-server:
    build: .
    ports:
      - "8585:8585"  # 8000:8000'den değiştir
    environment:
      - ENVIRONMENT=development
      - PORT=8585  
      - REDIS_URL=redis://redis:6379/0
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - .:/app
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes

volumes:
  redis_data:
